# --- Sample dataset

# --- !Ups
insert into egg (id, name, distance) values (1, 'Bulbasaur', 2);
insert into egg (id, name, distance) values (4, 'Charmander', 2);
insert into egg (id, name, distance) values (7, 'Squirtle', 2);
insert into egg (id, name, distance) values (10, 'Caterpie', 2);
insert into egg (id, name, distance) values (13, 'Weedle', 2);
insert into egg (id, name, distance) values (16, 'Pidgey', 2);
insert into egg (id, name, distance) values (19, 'Rattata', 2);
insert into egg (id, name, distance) values (21, 'Pearow', 2);
insert into egg (id, name, distance) values (25, 'Pikachu', 2);
insert into egg (id, name, distance) values (35, 'Clefairy', 2);
insert into egg (id, name, distance) values (39, 'Jigglypuff', 2);
insert into egg (id, name, distance) values (41, 'Zubat', 2);
insert into egg (id, name, distance) values (74, 'Geodude', 2);
insert into egg (id, name, distance) values (129, 'Magikarp', 2);
insert into egg (id, name, distance) values (23 , 'Ekans', 5);
insert into egg (id, name, distance) values (27 , 'Sandshrew', 5);
insert into egg (id, name, distance) values (29 , 'Nidoran♀', 5);
insert into egg (id, name, distance) values (32 , 'Nidoran♂', 5);
insert into egg (id, name, distance) values (37 , 'Vulpix', 5);
insert into egg (id, name, distance) values (43 , 'Oddish', 5);
insert into egg (id, name, distance) values (46 , 'Paras', 5);
insert into egg (id, name, distance) values (48 , 'Venonat', 5);
insert into egg (id, name, distance) values (50 , 'Diglett', 5);
insert into egg (id, name, distance) values (52 , 'Meowth', 5);
insert into egg (id, name, distance) values (54 , 'Psyduck', 5);
insert into egg (id, name, distance) values (56 , 'Mankey', 5);
insert into egg (id, name, distance) values (58 , 'Growlithe', 5);
insert into egg (id, name, distance) values (60 , 'Poliwag', 5);
insert into egg (id, name, distance) values (63 , 'Abra', 5);
insert into egg (id, name, distance) values (66 , 'Machop', 5);
insert into egg (id, name, distance) values (69 , 'Bellsprout', 5);
insert into egg (id, name, distance) values (72 , 'Tentacool', 5);
insert into egg (id, name, distance) values (77 , 'Ponyta', 5);
insert into egg (id, name, distance) values (79 , 'Slowpoke', 5);
insert into egg (id, name, distance) values (81 , 'Magnemite', 5);
insert into egg (id, name, distance) values (83 , 'Farfetch''d', 5);
insert into egg (id, name, distance) values (84 , 'Doduo', 5);
insert into egg (id, name, distance) values (86 , 'Seel', 5);
insert into egg (id, name, distance) values (88 , 'Grimer', 5);
insert into egg (id, name, distance) values (90 , 'Shellder', 5);
insert into egg (id, name, distance) values (92 , 'Gastly', 5);
insert into egg (id, name, distance) values (96 , 'Drowzee', 5);
insert into egg (id, name, distance) values (98 , 'Krabby', 5);
insert into egg (id, name, distance) values (100, 'Voltorb', 5);
insert into egg (id, name, distance) values (102, 'Exeggcute', 5);
insert into egg (id, name, distance) values (104, 'Cubone', 5);
insert into egg (id, name, distance) values (108, 'Lickitung', 5);
insert into egg (id, name, distance) values (109, 'Koffing', 5);
insert into egg (id, name, distance) values (111, 'Rhyhorn', 5);
insert into egg (id, name, distance) values (114, 'Tangela', 5);
insert into egg (id, name, distance) values (115, 'Kangaskhan', 5);
insert into egg (id, name, distance) values (116, 'Horsea', 5);
insert into egg (id, name, distance) values (118, 'Goldeen', 5);
insert into egg (id, name, distance) values (120, 'Staryu', 5);
insert into egg (id, name, distance) values (128, 'Tauros', 5);
insert into egg (id, name, distance) values (137, 'Porygon', 5);
insert into egg (id, name, distance) values (95 , 'Onix', 10);
insert into egg (id, name, distance) values (106, 'Hitmonlee', 10);
insert into egg (id, name, distance) values (107, 'Hitmonchan', 10);
insert into egg (id, name, distance) values (113, 'Chansey', 10);
insert into egg (id, name, distance) values (122, 'Mr. Mime', 10);
insert into egg (id, name, distance) values (123, 'Scyther', 10);
insert into egg (id, name, distance) values (124, 'Jynx', 10);
insert into egg (id, name, distance) values (125, 'Electabuzz', 10);
insert into egg (id, name, distance) values (126, 'Magmar', 10);
insert into egg (id, name, distance) values (127, 'Pinsir', 10);
insert into egg (id, name, distance) values (131, 'Lapras', 10);
insert into egg (id, name, distance) values (133, 'Eevee', 10);
insert into egg (id, name, distance) values (138, 'Omanyte', 10);
insert into egg (id, name, distance) values (140, 'Kabuto', 10);
insert into egg (id, name, distance) values (142, 'Aerodactyl', 10);
insert into egg (id, name, distance) values (143, 'Snorlax', 10);
insert into egg (id, name, distance) values (147, 'Dratini', 10);

insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (1,'Bulbasaur','Grass','Poison',90,126,126,16,10,1071,10,29,25,2);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (2,'Ivysaur','Grass','Poison',120,156,158,8,7,1632,23,8,100,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (3,'Venusaur','Grass','Poison',160,198,200,4,5,2580,11,4,-1,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (4,'Charmander','Fire','None',78,128,108,16,10,955,29,10,25,2);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (5,'Charmeleon','Fire','None',116,160,140,8,7,1557,23,8,100,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (6,'Charizard','Fire','Flying',156,212,182,4,5,2602,11,4,-1,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (7,'Squirtle','Water','None',88,112,142,16,10,1008,10,29,25,2);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (8,'Wartortle','Water','None',118,144,176,8,7,1582,23,8,100,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (9,'Blastoise','Water','None',158,186,222,4,5,2542,14,5,-1,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (10,'Caterpie','Bug','None',90,62,66,40,20,443,10,29,12,2);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (11,'Metapod','Bug','None',100,56,86,20,9,477,3600,3600,50,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (12,'Butterfree','Bug','Flying',120,144,144,10,6,1454,6,17,-1,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (13,'Weedle','Bug','Poison',80,68,64,40,20,449,10,29,12,2);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (14,'Kakuna','Bug','Poison',90,62,82,20,9,485,3600,3600,50,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (15,'Beedrill','Bug','Poison',130,144,130,10,6,1439,6,17,-1,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (16,'Pidgey','Normal','Flying',80,94,90,40,20,679,10,29,12,2);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (17,'Pidgeotto','Normal','Flying',126,126,122,20,9,1223,10,29,50,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (18,'Pidgeot','Normal','Flying',166,170,166,10,6,2091,6,17,-1,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (19,'Rattata','Normal','None',60,92,86,40,20,581,10,29,25,2);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (20,'Raticate','Normal','None',110,146,150,16,7,1444,23,8,-1,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (21,'Spearow','Normal','Flying',80,102,78,40,15,686,10,29,50,2);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (22,'Fearow','Normal','Flying',130,168,146,16,7,1746,8,23,-1,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (23,'Ekans','Poison','None',70,112,112,40,15,824,29,10,50,5);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (24,'Arbok','Poison','None',120,166,166,16,7,1767,23,8,-1,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (25,'Pikachu','Electric','None',70,124,108,16,10,887,10,29,50,2);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (26,'Raichu','Electric','None',120,200,154,8,6,2028,6,17,-1,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (27,'Sandshrew','Ground','None',100,90,114,40,10,798,8,23,50,5);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (28,'Sandslash','Ground','None',150,150,172,16,6,1810,11,4,-1,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (29,'Nidoran♀','Poison','None',110,100,104,40,15,876,29,10,25,5);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (30,'Nidorina','Poison','None',140,132,136,20,7,1404,23,8,50,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (31,'Nidoqueen','Poison','Ground',180,184,190,10,5,2485,14,5,-1,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (32,'Nidoran♂','Poison','None',92,110,94,40,15,843,29,10,25,5);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (33,'Nidorino','Poison','None',122,142,128,20,7,1372,23,8,50,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (34,'Nidoking','Poison','Ground',162,204,170,10,5,2475,14,5,-1,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (35,'Clefairy','Fairy','None',140,116,124,24,10,1200,8,23,50,2);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (36,'Clefable','Fairy','None',190,178,178,8,6,2397,4,11,-1,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (37,'Vulpix','Fire','None',76,106,118,24,10,831,10,29,50,5);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (38,'Ninetales','Fire','None',146,176,194,8,6,2188,5,14,-1,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (39,'Jigglypuff','Normal','Fairy',230,98,54,40,10,917,10,29,50,2);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (40,'Wigglytuff','Normal','Fairy',280,168,108,16,6,2177,4,11,-1,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (41,'Zubat','Poison','Flying',80,88,90,40,20,642,10,29,50,2);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (42,'Golbat','Poison','Flying',150,164,164,16,7,1921,6,17,-1,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (43,'Oddish','Grass','Poison',90,134,130,48,15,1148,10,29,25,5);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (44,'Gloom','Grass','Poison',120,162,158,24,7,1689,8,23,100,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (45,'Vileplume','Grass','Poison',150,202,190,12,5,2492,11,4,-1,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (46,'Paras','Bug','Grass',70,122,120,32,15,916,29,10,50,5);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (47,'Parasect','Bug','Grass',120,162,170,16,7,1747,17,6,-1,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (48,'Venonat','Bug','Poison',120,108,118,40,15,1029,10,29,50,5);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (49,'Venomoth','Bug','Poison',140,172,154,16,7,1890,6,17,-1,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (50,'Diglett','Ground','None',20,108,86,40,10,456,29,10,50,5);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (51,'Dugtrio','Ground','None',70,148,140,16,6,1168,29,10,-1,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (52,'Meowth','Normal','None',80,104,94,40,15,756,29,10,50,5);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (53,'Persian','Normal','None',130,156,146,16,7,1631,8,23,-1,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (54,'Psyduck','Water','None',100,132,112,40,10,1109,10,29,50,5);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (55,'Golduck','Water','None',160,194,176,16,6,2386,5,14,-1,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (56,'Mankey','Fighting','None',80,122,96,40,10,878,29,10,50,5);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (57,'Primeape','Fighting','None',130,178,150,16,6,1864,17,6,-1,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (58,'Growlithe','Fire','None',110,156,110,24,10,1335,10,29,50,5);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (59,'Arcanine','Fire','None',180,230,180,8,6,2983,4,11,-1,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (60,'Poliwag','Water','None',80,108,98,40,15,795,10,29,25,5);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (61,'Poliwhirl','Water','None',130,132,132,20,7,1340,8,23,100,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (62,'Poliwrath','Water','Fighting',180,180,202,10,5,2505,11,4,-1,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (63,'Abra','Psychic','None',50,110,76,40,99,600,29,10,25,5);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (64,'Kadabra','Psychic','None',80,150,112,20,7,1131,6,17,100,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (65,'Alakazam','Psychic','None',110,186,152,10,5,1813,4,11,-1,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (66,'Machop','Fighting','None',140,118,96,40,10,1089,23,8,25,5);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (67,'Machoke','Fighting','None',160,154,144,20,7,1760,14,5,100,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (68,'Machamp','Fighting','None',180,198,180,10,5,2594,8,3,-1,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (69,'Bellsprout','Grass','Poison',100,158,78,40,15,1117,10,29,25,5);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (70,'Weepinbell','Grass','Poison',130,190,110,20,7,1723,8,23,100,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (71,'Victreebel','Grass','Poison',160,222,152,10,5,2530,14,5,-1,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (72,'Tentacool','Water','Poison',80,106,136,40,15,905,23,8,50,5);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (73,'Tentacruel','Water','Poison',160,170,196,16,7,2220,11,4,-1,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (74,'Geodude','Rock','Ground',80,106,118,40,10,849,8,23,25,2);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (75,'Graveler','Rock','Ground',110,142,156,20,7,1433,14,5,100,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (76,'Golem','Rock','Ground',160,176,198,10,5,2303,8,3,-1,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (77,'Ponyta','Fire','None',100,168,138,32,10,1516,8,23,50,5);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (78,'Rapidash','Fire','None',130,200,170,12,6,2199,6,17,-1,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (79,'Slowpoke','Water','Psychic',180,110,110,40,10,1218,8,23,50,5);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (80,'Slowbro','Water','Psychic',190,184,198,16,6,2597,3,8,-1,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (81,'Magnemite','Electric','Steel',50,128,138,40,10,890,8,23,50,5);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (82,'Magneton','Electric','Steel',100,186,180,16,6,1879,5,14,-1,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (83,'Farfetch''d','Normal','Flying',104,138,132,24,9,1263,29,10,-1,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (84,'Doduo','Normal','Flying',70,126,96,40,10,855,10,29,50,5);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (85,'Dodrio','Normal','Flying',120,182,150,16,6,1836,6,17,-1,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (86,'Seel','Water','None',130,104,138,40,9,1107,10,29,50,5);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (87,'Dewgong','Water','Ice',180,156,192,16,6,2145,5,14,-1,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (88,'Grimer','Poison','None',160,124,110,40,10,1284,23,8,50,5);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (89,'Muk','Poison','None',210,180,188,16,6,2602,8,3,-1,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (90,'Shellder','Water','None',60,120,112,40,10,822,23,8,50,5);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (91,'Cloyster','Water','Ice',100,196,196,16,6,2052,3,8,-1,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (92,'Gastly','Ghost','Poison',60,136,82,32,10,804,29,10,25,5);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (93,'Haunter','Ghost','Poison',90,172,118,16,7,1380,23,8,100,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (94,'Gengar','Ghost','Poison',120,204,156,8,5,2078,14,5,-1,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (95,'Onix','Rock','Ground',70,90,186,16,9,857,17,6,-1,10);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (96,'Drowzee','Psychic','None',120,104,140,40,10,1075,8,23,50,5);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (97,'Hypno','Psychic','None',170,162,196,16,6,2184,11,4,-1,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (98,'Krabby','Water','None',60,116,110,40,15,792,23,8,50,5);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (99,'Kingler','Water','None',110,178,168,16,7,1823,8,3,-1,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (100,'Voltorb','Electric','None',80,102,124,40,10,839,10,29,50,5);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (101,'Electrode','Electric','None',120,150,174,16,6,1646,8,23,-1,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (102,'Exeggcute','Grass','Psychic',120,110,132,40,10,1099,8,23,50,5);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (103,'Exeggutor','Grass','Psychic',190,232,164,16,6,2955,8,3,-1,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (104,'Cubone','Ground','None',100,102,150,32,10,1006,8,23,50,5);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (105,'Marowak','Ground','None',120,140,202,12,6,1656,14,5,-1,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (106,'Hitmonlee','Fighting','None',100,148,172,16,9,1492,11,4,-1,10);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (107,'Hitmonchan','Fighting','None',100,138,204,16,9,1516,14,5,-1,10);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (108,'Lickitung','Normal','None',180,126,160,16,9,1626,23,8,-1,5);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (109,'Koffing','Poison','None',80,136,142,40,10,1151,8,23,50,5);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (110,'Weezing','Poison','None',130,190,198,16,6,2250,4,11,-1,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (111,'Rhyhorn','Ground','Rock',160,110,116,40,10,1182,14,5,50,5);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (112,'Rhydon','Ground','Rock',210,166,160,16,6,2243,8,3,-1,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (113,'Chansey','Normal','None',500,40,60,16,9,675,3,8,-1,10);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (114,'Tangela','Grass','None',130,164,152,32,9,1739,4,11,-1,5);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (115,'Kangaskhan','Normal','None',210,142,178,16,9,2043,11,4,-1,5);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (116,'Horsea','Water','None',60,122,100,40,10,794,10,29,50,5);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (117,'Seadra','Water','None',110,176,150,16,6,1713,6,17,-1,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (118,'Goldeen','Water','None',90,112,126,40,15,965,10,29,50,5);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (119,'Seaking','Water','None',160,172,160,16,7,2043,14,5,-1,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (120,'Staryu','Water','None',60,130,128,40,15,937,10,29,50,5);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (121,'Starmie','Water','Psychic',120,194,192,16,6,2182,6,17,-1,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (122,'Mr.Mime','Psychic','Fairy',80,154,196,24,9,1494,5,14,-1,10);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (123,'Scyther','Bug','Flying',140,176,180,24,9,2073,14,5,-1,10);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (124,'Jynx','Ice','Psychic',130,172,134,24,9,1716,4,11,-1,10);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (125,'Electabuzz','Electric','None',130,198,160,24,9,2119,6,17,-1,10);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (126,'Magmar','Fire','None',130,214,158,24,9,2265,14,5,-1,10);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (127,'Pinsir','Bug','None',130,184,186,24,9,2121,8,3,-1,10);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (128,'Tauros','Normal','None',150,148,184,24,9,1844,4,11,-1,5);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (129,'Magikarp','Water','None',40,42,84,56,15,262,3600,3600,400,2);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (130,'Gyarados','Water','Flying',190,192,196,8,7,2688,8,3,-1,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (131,'Lapras','Water','Ice',260,186,190,16,9,2980,3,8,-1,10);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (132,'Ditto','Normal','None',96,110,110,16,10,919,3600,3600,-1,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (133,'Eevee','Normal','None',110,114,128,32,10,1077,10,29,25,10);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (134,'Vaporeon','Water','None',260,186,168,12,6,2816,3,8,-1,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (135,'Jolteon','Electric','None',130,192,174,12,6,2140,4,11,-1,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (136,'Flareon','Fire','None',130,238,178,12,6,2643,3,8,-1,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (137,'Porygon','Normal','None',130,156,158,32,9,1691,8,23,-1,5);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (138,'Omanyte','Rock','Water',70,132,160,32,9,1119,8,23,50,10);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (139,'Omastar','Rock','Water',140,180,202,12,5,2233,3,8,-1,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (140,'Kabuto','Rock','Water',60,148,142,32,9,1104,8,23,50,10);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (141,'Kabutops','Rock','Water',120,190,190,12,5,2130,11,4,-1,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (142,'Aerodactyl','Rock','Flying',160,182,162,16,9,2165,5,14,-1,10);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (143,'Snorlax','Normal','None',320,180,180,16,9,3112,3,8,-1,10);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (144,'Articuno','Ice','Flying',180,198,242,0,10,2978,3,8,-1,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (145,'Zapdos','Electric','Flying',180,232,194,0,10,3114,3,8,-1,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (146,'Moltres','Fire','Flying',180,242,194,0,10,3240,3,8,-1,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (147,'Dratini','Dragon','None',82,128,110,32,9,983,10,29,25,10);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (148,'Dragonair','Dragon','None',122,170,152,8,6,1747,8,23,100,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (149,'Dragonite','Dragon','Flying',182,250,212,4,5,3500,3,8,-1,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (150,'Mewtwo','Psychic','None',212,284,202,0,10,4144,8,3,-1,-1);
insert into pokemon (id, name, type1, type2, hp, attack, defence, capture_rate, escape_rate, max_cp, move_interval, attack_interval, evolve_candy, distance) values (151,'Mew','Psychic','None',200,220,220,0,10,3299,3,8,-1,-1);

insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (1,'Fire Fang','Fire',7,0,840,4);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (2,'Ember','Fire',10,0,1050,7);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (3,'Flame Burst','Fire',25,5,2100,-25);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (4,'Fire Punch','Fire',35,5,2800,-33);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (5,'Flamethrower','Fire',50,5,2900,-50);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (6,'Flame Charge','Fire',25,5,3100,-20);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (7,'Heat Wave','Fire',60,5,3800,-100);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (8,'Fire Blast','Fire',60,5,4100,-100);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (9,'Flame Wheel','Fire',35,5,4600,-25);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (10,'Water Gun','Water',10,0,500,7);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (11,'Bubble','Water',15,0,2300,15);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (12,'Aqua Tail','Water',50,5,2350,-50);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (13,'Aqua Jet','Water',15,5,2350,-20);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (14,'Brine','Water',15,5,2400,-25);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (15,'Bubble Beam','Water',25,5,2900,-25);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (16,'Water Pulse','Water',30,5,3300,-25);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (17,'Hydro Pump','Water',60,5,3800,-100);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (18,'Scald','Water',35,5,4000,-33);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (19,'Vine Whip','Grass',10,0,650,7);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (20,'Razor Leaf','Grass',15,0,1450,7);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (21,'Seed Bomb','Grass',30,5,2400,-33);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (22,'Power Whip','Grass',60,0,2800,-100);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (23,'Leaf Blade','Grass',45,25,2800,-50);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (24,'Mega Drain','Grass',0,5,3200,-20);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (25,'Petal Blizzard','Grass',50,5,3200,-50);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (26,'Giga Drain','Grass',0,5,3600,-33);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (27,'Solar Beam','Grass',65,5,4900,-100);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (28,'Thunder Shock','Electric',5,0,600,7);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (29,'Spark','Electric',7,0,700,4);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (30,'Parabolic Charge','Electric',0,5,2100,-20);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (31,'Thunder Punch','Electric',40,5,2400,-33);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (32,'Discharge','Electric',40,5,2500,-33);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (33,'Thunderbolt','Electric',50,5,2700,-50);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (34,'Thunder','Electric',65,5,4300,-100);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (35,'Scratch','Normal',10,0,500,7);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (36,'Pound','Normal',8,0,540,7);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (37,'Tackle','Normal',12,0,1100,7);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (38,'Cut','Normal',0,0,1130,7);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (39,'Splash','Normal',0,0,1230,7);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (40,'Quick Attack','Normal',10,0,1330,7);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (41,'Body Slam','Normal',50,5,1560,-50);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (42,'Struggle','Normal',15,0,1695,-20);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (43,'Vice Grip','Normal',15,5,2100,-20);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (44,'Stomp','Normal',25,5,2100,-25);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (45,'Hyper Fang','Normal',35,5,2100,-33);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (46,'Horn Attack','Normal',20,5,2200,-25);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (47,'Swift','Normal',25,5,3000,-25);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (48,'Wrap','Normal',15,5,4000,-20);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (49,'Hyper Beam','Normal',70,5,5000,-100);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (50,'Low Kick','Fighting',5,0,600,7);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (51,'Karate Chop','Fighting',6,0,800,7);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (52,'Rock Smash','Fighting',5,0,1410,7);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (53,'Brick Break','Fighting',30,25,1600,-33);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (54,'Cross Chop','Fighting',55,25,2000,-100);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (55,'Submission','Fighting',30,5,2100,-33);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (56,'Low Sweep','Fighting',25,5,2250,-25);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (57,'Wing Attack','Flying',12,0,750,7);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (58,'Peck','Flying',10,0,1150,10);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (59,'Drill Peck','Flying',30,5,2700,-33);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (60,'Aerial Ace','Flying',25,5,2900,-25);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (61,'Hurricane','Flying',60,5,3200,-100);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (62,'Air Cutter','Flying',25,25,3300,-25);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (63,'Fury Cutter','Bug',3,0,400,12);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (64,'Bug Bite','Bug',6,0,450,7);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (65,'X-Scissor','Bug',30,5,2100,-33);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (66,'Signal Beam','Bug',35,5,3100,-33);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (67,'Megahorn','Bug',55,5,3200,-100);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (68,'Bug Buzz','Bug',50,5,4250,-50);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (69,'Poison Sting','Poison',6,0,575,4);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (70,'Poison Jab','Poison',15,0,1050,7);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (71,'Acid','Poison',10,0,1050,7);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (72,'Cross Poison','Poison',20,25,1500,-25);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (73,'Poison Fang','Poison',15,5,2400,-20);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (74,'Sludge Bomb','Poison',50,5,2600,-50);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (75,'Sludge','Poison',25,5,2600,-25);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (76,'Gunk Shot','Poison',60,5,3000,-100);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (77,'Sludge Wave','Poison',60,5,3400,-100);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (78,'Rock Throw','Rock',12,0,1360,7);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (79,'Power Gem','Rock',40,5,2900,-33);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (80,'Stone Edge','Rock',55,50,3100,-100);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (81,'Rock Slide','Rock',40,5,3200,-33);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (82,'Rock Tomb','Rock',25,25,3400,-25);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (83,'Ancient Power','Rock',30,5,3600,-25);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (84,'Mud Shot','Ground',12,0,550,7);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (85,'Mud Slap','Ground',6,0,1350,9);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (86,'Bone Club','Ground',20,5,1600,-25);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (87,'Mud Bomb','Ground',25,5,2600,-25);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (88,'Drill Run','Ground',30,25,3400,-33);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (89,'Bulldoze','Ground',30,5,3400,-25);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (90,'Earthquake','Ground',60,5,4200,-100);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (91,'Dig','Ground',45,5,5800,-33);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (92,'Metal Claw','Steel',12,0,630,7);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (93,'Bullet Punch','Steel',10,0,1200,7);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (94,'Steel Wing','Steel',15,0,1330,4);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (95,'Iron Head','Steel',40,5,2000,-33);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (96,'Magnet Bomb','Steel',25,5,2800,-25);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (97,'Flash Cannon','Steel',55,5,3900,-33);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (98,'Frost Breath','Ice',12,0,810,7);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (99,'Ice Shard','Ice',10,0,1400,7);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (100,'Ice Punch','Ice',45,5,3500,-33);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (101,'Ice Beam','Ice',50,5,3650,-50);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (102,'Icy Wind','Ice',15,5,3800,-20);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (103,'Blizzard','Ice',60,5,3900,-100);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (104,'Psycho Cut','Psychic',15,0,570,7);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (105,'Zen Headbutt','Psychic',15,0,1050,4);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (106,'Confusion','Psychic',12,0,1510,7);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (107,'Heart Stamp','Psychic',0,5,2550,-25);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (108,'Psyshock','Psychic',40,5,2700,-33);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (109,'Psychic','Psychic',50,5,2800,-50);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (110,'Rest','Psychic',0,0,3100,-33);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (111,'Psybeam','Psychic',35,5,3800,-25);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (112,'Psystrike','Psychic',0,5,5100,-100);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (113,'Bite','Dark',6,0,500,7);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (114,'Sucker Punch','Dark',7,0,700,4);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (115,'Feint Attack','Dark',12,0,1040,7);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (116,'Night Slash','Dark',25,25,2700,-25);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (117,'Dark Pulse','Dark',45,5,3500,-33);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (118,'Lick','Ghost',10,0,500,7);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (119,'Shadow Claw','Ghost',16,0,950,7);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (120,'Shadow Punch','Ghost',0,5,2100,-25);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (121,'Shadow Ball','Ghost',40,5,3080,-33);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (122,'Ominous Wind','Ghost',25,5,3100,-25);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (123,'Shadow Sneak','Ghost',0,5,3100,-20);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (124,'Dragon Breath','Dragon',6,0,500,7);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (125,'Dragon Claw','Dragon',40,25,1500,-50);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (126,'Twister','Dragon',15,5,2700,-20);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (127,'Dragon Pulse','Dragon',50,5,3600,-50);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (128,'Draining Kiss','Fairy',15,5,2800,-20);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (129,'Play Rough','Fairy',50,5,2900,-50);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (130,'Disarming Voice','Fairy',20,5,3900,-20);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (131,'Moonblast','Fairy',60,5,4100,-100);
insert into move (id, name, move_type, power, critical_hit_rate, cooldown, energy_inc) values (132,'Dazzling Gleam','Fairy',45,5,4200,-33);

# --- !Downs


